name: Authenticate to Google Cloud

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2.1.3'
        with:
          credentials_json: '${{ secrets.bananasplit }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Set region for Cloud Run'
        run: 'gcloud config set run/region us-central1'

      - name: 'Run rookiespaymentapp'
        run: 'gcloud run deploy rookiespaymentapp --source . --allow-unauthenticated'
